### ISSUE TITLE
Ошибка установки из npm'а

### ISSUE THREAD

**Issue by AlexeyAndKartashov** [koorchik/node-mystem3#1]
Приветствую!

Не могу установить пакет из npm'а, потому что npm ругается на вот это:

```
> bin/download-mystem.js
"bin" не является внутренней или внешней командой, исполняемой программой или пакетным файлом.
```

Подозреваю, что вот в этой строчке:
https://github.com/koorchik/node-mystem3/blob/1f3bdee4045c7a1b3fd8dcd2610157d61363a594/package.json#L7
надо вначало добавить node.
Т.е. вместо `bin/download-mystem.js` надо `node bin/download-mystem.js`.

Обновите, пожалуйста! Заранее спасибо)

**Comment by koorchik** [comment]
Проблема под виндовс?

**Comment by koorchik** [comment]
node bin/download-mystem.js поставил.

**Comment by AlexeyAndKartashov** [comment]
Да, под win 7 32.

Исправилась вот так:
https://github.com/antixrist/node-mystem3/commit/03dfc01bfe47310ab67d554b4cec95e6da3edcaf#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R7
https://github.com/antixrist/node-mystem3/commit/03dfc01bfe47310ab67d554b4cec95e6da3edcaf#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L7

**Comment by koorchik** [comment]
обновил на npm

**Comment by AlexeyAndKartashov** [comment]
Во второй ссылке ошибся. Там ещё индентификатор системы пришлось поправить (тоже ошибку выкидывал):
https://github.com/antixrist/node-mystem3/commit/b300276ddd055c8453c28a28aa6a403b45a69675#diff-54e0dafe731ea6d5bee7b960f28f35b5R19
