### ISSUE TITLE
Support for Node 10

### ISSUE THREAD

**Issue by Kunya** [koorchik/node-mystem3#5]
Добрый день,

Вижу что установка из npm с 10-й нодой падает
https://travis-ci.org/koorchik/node-mystem3/jobs/436059240
На локальной машине под виндой итог такой же.

Вопрос, можно ли это как-то починить или проще откатиться на 9-ю ноду?

Спасибо!
Саша

**Comment by Kunya** [comment]
npm версия 6.4.1, node v10.15.3

**Comment by koorchik** [comment]
Исправил:
1. Должно работать в node 10 и 12
2. Обновил mystem до версии 3.1 (для платформ, где это доступно было)
3. Добавил поддерку Windows.
4. Расширил CI конфигурацию (https://travis-ci.org/koorchik/node-mystem3) 
5. Опубликовал на  npm (версия 1.2.1)

**Comment by Kunya** [comment]
Спасибо большое!!
